### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by sonik22** [harryhaaren/showq#12]
Compiling showq on manjaro (arch) needs some adjustements:
Pointing to python2 (instead of python, which will call python3) in two files:
/waf and /src/wscript
and change the last line of /src/wscript to
  '-DPROGRAMNAME_LOCALEDIR=\"${PREFIX}/share/locale/\"', '-std=c++11']
)

**Comment by harryhaaren** [comment]
Hi @sonik22,

Why is C++ 11 needed? I dont think it should be..

Cheers, -Harry

**Comment by sonik22** [comment]
I have no idea, as i am no coder, i did that with a friend who uses arch and he pointed me to these changings to get it compiled. Maybe there are other ways, but without changing to c++11 showq didn't want to install.

**Comment by harryhaaren** [comment]
Ok. The issue with adding C++11 to the flags is that older systems may not be able to compile it - and since this is packaged for various (older) distros, its not a good idea to add it without it being necessary everywhere.

As it compiles fine on a Debian Jessie system without the C++11 flag, I'll mark this bug as closed.

Thanks @sonik22 for reporting - any Manjaro / Arch users who encounter the same issue will find this issue with a little google-fu, and then have a solution :) Cheers, -Harry

**Comment by sonik22** [comment]
That's fine for me :-)

Cheers
