### ISSUE TITLE
Trigger hotkeys not saved with session

### ISSUE THREAD

**Issue by nettings** [harryhaaren/showq#3]
- Assign a hotkey to a cue.
- Save session.
- Quit program, restart, restore session
- Hotkey is now disabled.

Simple yet important missing feature :)

**Comment by harryhaaren** [comment]
Confirmed, will (try) fix this later today / tomorrow.

**Comment by harryhaaren** [comment]
The issue is in the XML parsing - somehow the description field and hotkey field are being stored in the same m_text variable on loading, which causes the hotkey parsing to not work.

`waveCueDscript` is the description of the Cue, and `x` used as the keyboard hotkey for the Cue.
Current (wrong) output:

```
waveCueDscript

        x
```

It should be two seperate pieces of info: `waveCureDscript` and `x`.
